/* =============================================================================
 * TYPE DEFINITIONS
 * ============================================================================= */

// Raw file data straight from the browser's FileReader API
// This is what we get immediately after the user uploads a file
export interface rawData {
  filename: string;                    // Original filename from user's computer
  content: string | Uint8Array;        // Text content or binary data
  size: number;                        // File size in bytes
  type: string;                        // MIME type (text/plain, application/pdf, etc.)
}

// Structured file data ready for IndexedDB storage
// We convert everything to strings and add metadata before storing
export interface fileData {
  id?: number;                         // Auto-generated by Dexie (undefined before insertion)
  filename: string;                    // Original filename preserved
  content: string;                     // Always a string (binary data gets Base64-encoded)
  size: number;                        // File size in bytes
  type: string;                        // MIME type preserved for icon/display logic
  createdAt?: number;                  // Unix timestamp - when file was uploaded
  processedContent?: string;           // ML output - populated after running CRF model
}

/* =============================================================================
 * DATA TRANSFORMATION UTILITIES
 * ============================================================================= */

// Convert binary file data to Base64 string for storage
// We do this because IndexedDB can't efficiently store Uint8Array in our schema
// Base64 is ~33% larger but lets us treat all content uniformly as strings
function uint8ArrayToBase64(uint8Array: Uint8Array): string {
  let binary = '';
  const len = uint8Array.byteLength;
  
  // Build a binary string by converting each byte to a character
  for (let i = 0; i < len; i++) {
    binary += String.fromCharCode(uint8Array[i]);
  }
  
  // Use browser's built-in Base64 encoder
  return btoa(binary);
}

// Transform raw uploaded files into database-ready format
// This is the bridge between the browser's File API and our IndexedDB schema
export function mapData(rawDataArray: rawData[]): fileData[] {
  return rawDataArray.map((rawItem) => {
    // Binary files (PDF, DOCX) get Base64-encoded
    // Text files stay as-is since they're already strings
    const content =
      rawItem.content instanceof Uint8Array
        ? uint8ArrayToBase64(rawItem.content)
        : rawItem.content;
    
    // Add timestamp - useful for sorting and showing "uploaded 5 minutes ago"
    return {
      filename: rawItem.filename,
      content,
      size: rawItem.size,
      type: rawItem.type,
      createdAt: Date.now(),
    };
  });
}