#
# Docstrings generated by VS Code Python Docstring Generator and modified by Evan Halperin
#

import json
from sklearn_crfsuite import CRF

from aliases import DataDict, DatasetFeatures, DatasetLabels, MorphList, DatasetMarginals, ConfidenceData
from process_data import process_data
from features import get_labeled_features, get_unlabeled_features
from model import build_crf
from evaluate import reconstruct_predictions, evaluate_predictions, get_confidence_data

def run(config_json: str) -> str:
	"""
	Config contains:
		- train_tgt: str
		- test_tgt: str
		- select_src: str
		- method: str
		- increment_size: int
		- current_cycle: int
		- max_crf_iterations: int
		- delta: int

	Eventually, we want to move from the config containing the entire train, test, and select file content
	to only containing the file path, so we can just read from it.
	"""
	config: dict = json.loads(config_json)

	data: DataDict = process_data(config['train_tgt'], config['test_tgt'], config['select_src'])

	X_train: DatasetFeatures
	y_train: DatasetLabels
	X_train, y_train = get_labeled_features(data['train']['words'], data['train']['bmes'], config['delta'])

	X_test: DatasetFeatures
	y_test: DatasetLabels
	X_test, y_test = get_labeled_features(data['test']['words'], data['test']['bmes'], config['delta'])

	crf: CRF = build_crf(X_train, y_train, config['max_iterations'])

	y_test_predict: DatasetLabels = crf.predict(X_test)
	test_predictions: list[MorphList] = reconstruct_predictions(y_test_predict, data['test']['words'])

	precision: float
	recall: float
	f1: float
	precision, recall, f1 = evaluate_predictions(data['test']['morphs'], test_predictions)
	
	X_select = get_unlabeled_features(data['select']['words'], config['delta'])
	y_select_predict: DatasetLabels = crf.predict(X_select)
	marginals: DatasetMarginals = crf.predict_marginals(X_select)
	confidence_data: list[ConfidenceData] = get_confidence_data(data['select']['words'], y_select_predict, marginals)
	
	increment_words: list[str] = [word for word, _ in confidence_data[:config['increment_size']]]
	residual_words: list[str] = [word for word, _ in confidence_data[config['increment_size']:]]

	print(increment_words)
	print(residual_words)

if __name__ == '__main__':
	config: dict = {
		'train_tgt': 'hello\ngood!bye\ngood!night',
		'test_tgt': 'goodie\ngood!thing',
		'select_src': 'good!bye\ngoodie\nnonsense',
		'method': None,
		'increment_size': 1,
		'current_cycle': 0,
		'max_iterations': 5,
		'delta': 4
	}
	run(json.dumps(config))