#
# Docstrings generated by VS Code Python Docstring Generator and modified by Evan Halperin
#

import json
from aliases import DataDict
from process_data import process_data

def run(config_json: str) -> str:
	"""
	Config contains:
		- train_tgt: str
		- test_tgt: str
		- select_src: str
		- method: str
		- increment_size: int
		- current_cycle: int
		- max_crf_iterations: int
		- delta: int
	"""
	config: dict = json.loads(config_json)

	data: DataDict = process_data(config['train_tgt'], config['test_tgt'], config['select_src'])
	print(data)

if __name__ == '__main__':
	config: dict = {
		'train_tgt': 'hello\ngood!bye',
		'test_tgt': 'what\nrun!ning',
		'select_src': 'hello\nworld'
	}
	run(json.dumps(config))