#
# Docstrings generated by VS Code Python Docstring Generator and modified by Evan Halperin
#

import json
from sklearn_crfsuite import CRF

from aliases import DataDict, DatasetFeatures, DatasetLabels, MorphList, DatasetMarginals, ConfidenceData
from process_data import process_data
from features import get_labeled_features, get_unlabeled_features
from model import build_crf
from evaluate import reconstruct_predictions, evaluate_predictions, get_confidence_data, format_evaluation

def run(config_json: str) -> str:
	"""
	Config contains:
		- train_tgt: str
		- test_tgt: str
		- select_src: str
		- method: str
		- increment_size: int
		- current_cycle: int
		- max_crf_iterations: int
		- delta: int

	Eventually, we want to move from the config containing the entire train, test, and select file content
	to only containing the file path, so we can just read from it.
	"""
	try:
		config: dict = json.loads(config_json)

		data: DataDict = process_data(config['train_tgt'], config['test_tgt'], config['select_src'])

		X_train: DatasetFeatures
		y_train: DatasetLabels
		X_train, y_train = get_labeled_features(data['train']['words'], data['train']['bmes'], config['delta'])

		X_test: DatasetFeatures
		X_test, _ = get_labeled_features(data['test']['words'], data['test']['bmes'], config['delta'])

		crf: CRF = build_crf(X_train, y_train, config['max_iterations'])

		y_test_predict: DatasetLabels = crf.predict(X_test)
		test_predictions: list[MorphList] = reconstruct_predictions(y_test_predict, data['test']['words'])

		precision: float
		recall: float
		f1: float
		precision, recall, f1 = evaluate_predictions(data['test']['morphs'], test_predictions)
		evaluation_content: str = format_evaluation(
			data['test']['words'], data['test']['morphs'], test_predictions, precision, recall, f1
		)

		X_select = get_unlabeled_features(data['select']['words'], config['delta'])
		y_select_predict: DatasetLabels = crf.predict(X_select)
		marginals: DatasetMarginals = crf.predict_marginals(X_select)
		confidence_data: list[ConfidenceData] = get_confidence_data(data['select']['words'], y_select_predict, marginals)

		increment_words: list[str] = [word for word, _ in confidence_data[:config['increment_size']]]
		residual_words: list[str] = [word for word, _ in confidence_data[config['increment_size']:]]

		return json.dumps({
			'precision': precision,
			'recall': recall,
			'f1': f1,
			'incrementWords': increment_words,
			'residualCount': len(residual_words),
			'incrementContent': '\n'.join(increment_words),
			'residualContent': '\n'.join(residual_words),
			'evaluationContent': evaluation_content,
			'error': None,
		})
	except Exception:
		import traceback
		return json.dumps({
            'precision': 0.0,
            'recall': 0.0,
            'f1': 0.0,
            'incrementWords': [],
            'residualCount': 0,
            'incrementContent': '',
            'residualContent': '',
            'evaluationContent': '',
            'error': traceback.format_exc(),
        })

if __name__ == '__main__':
	config: dict = {
		'train_tgt': 'hello\ngood!bye\ngood!night',
		'test_tgt': 'goodie\ngood!thing',
		'select_src': 'good!bye\ngoodie\nnonsense',
		'method': None,
		'increment_size': 1,
		'current_cycle': 0,
		'max_iterations': 5,
		'delta': 4
	}
	run(json.dumps(config))